version: 2

models:
  - name: dim_user
    description: >
      Slowly Changing Dimension Type 2 (SCD2) for users.
      Tracks user attributes like email, address, and phone over time
      using surrogate key and valid_from / valid_to logic.
    columns:
      - name: dim_user_id
        description: Surrogate key for the user dimension (auto-incremented).
        tests:
          - not_null
          - unique

      - name: user_hkey
        description: Hash key from Data Vault model, uniquely identifies a user.
        tests:
          - not_null
          - unique  # Only one active record per user_hkey at a time

      - name: user_id
        description: The user's id.

      - name: user_name
        description: The user's name.

      - name: email
        description: Email address of the user.

      - name: phone_number
        description: Contact number.

      - name: address
        description: Residential address of the user.

      - name: birthdate
        description: Birth date of the user.

      - name: registration_date
        description: When the user registered.

      - name: valid_from
        description: Timestamp when this version of the record became valid.
        tests:
          - not_null

      - name: valid_to
        description: Timestamp when this version of the record expired. Defaults to 9999-12-31 for active records.
        tests:
          - not_null

  - name: dim_product
    description: >
      Slowly Changing Dimension Type 2 (SCD2) for product.
      Tracks user attributes like product anme, aisle, and department over time
      using surrogate key and valid_from / valid_to logic.
    columns:
      - name: product_hkey
        description: Hash key from Data Vault model, uniquely identifies a product.
        tests:
          - not_null
          - unique  # Only one active record per user_hkey at a time

      - name: user_idproduct_id
        description: The product's id.

      - name: product_name
        description: The product's name.

      - name: aisle_id
        description: aisle id for the product.

      - name: aisle
        description: aisle name for the product.

      - name: department_id
        description: department id for the product.

      - name: department
        description: department name for the product.

      - name: created_at
        description: When the record details was generated.

      - name: updated_at
        description: When the record details was updated.        

      - name: valid_from
        description: Timestamp when this version of the record became valid.
        tests:
          - not_null

      - name: valid_to
        description: Timestamp when this version of the record expired. Defaults to 9999-12-31 for active records.
        tests:
          - not_null