version: 2

models:
  - name: dim_user
    description: "DIM table for users, tracking historical changes with SCD2 methodology."
    materialized: table
    unique_key: user_hkey
    columns:
      - name: user_hkey
        description: "Surrogate key for the user."
        tests:
          - not_null
          - unique
      - name: user_id
        description: "Business key for the user, derived from user_id."
        tests:
          - not_null
      - name: name
        description: "Full name of the user."
      - name: email
        description: "Email address of the user (unique)."
        tests:
          - not_null
          - unique
      - name: birthdate
        description: "Birthdate of the user."
      - name: registration_date
        description: "Registration date of the user."
      - name: address
        description: "Address of the user."
      - name: phone_number
        description: "Phone number of the user."
      - name: start_date
        description: "The date when the user's information first became valid."
        tests:
          - not_null
      - name: end_date
        description: "The date when the user's information was no longer valid (for SCD2)."
      - name: current_flag
        description: "Flag indicating whether this record is the current version for the user."
        tests:
          - not_null
          - accepted_values:
              values: [True, False]

  # DIM table for products (SCD2)
  - name: dim_product
    description: "DIM table for products, tracking historical changes with SCD2 methodology."
    materialized: table
    unique_key: product_hkey
    columns:
      - name: product_hkey
        description: "Surrogate key for the product."
        tests:
          - not_null
          - unique
      - name: product_id
        description: "Business key for the product, derived from product_id."
        tests:
          - not_null
      - name: product_name
        description: "Product name."
        tests:
          - not_null
      - name: aisle_id
        description: "Aisle ID for the product."
      - name: department_id
        description: "Department ID for the product."
      - name: start_date
        description: "The date when the product's information first became valid."
        tests:
          - not_null
      - name: end_date
        description: "The date when the product's information was no longer valid (for SCD2)."
      - name: current_flag
        description: "Flag indicating whether this record is the current version for the product."
        tests:
          - not_null
          - accepted_values:
              values: [True, False]

  # DIM table for aisles (SCD2)
  - name: dim_aisle
    description: "DIM table for aisles, tracking historical changes with SCD2 methodology."
    materialized: table
    unique_key: aisle_hkey
    columns:
      - name: aisle_hkey
        description: "Surrogate key for the aisle."
        tests:
          - not_null
          - unique
      - name: aisle_id
        description: "Business key for the aisle."
        tests:
          - not_null
      - name: aisle_name
        description: "Aisle name."
        tests:
          - not_null
      - name: start_date
        description: "The date when the aisle's information first became valid."
        tests:
          - not_null
      - name: end_date
        description: "The date when the aisle's information was no longer valid (for SCD2)."
      - name: current_flag
        description: "Flag indicating whether this record is the current version for the aisle."
        tests:
          - not_null
          - accepted_values:
              values: [True, False]

