version: 2

models:
  - name: dim_user
    description: >
      Dimension table for users, capturing slowly changing attributes
      such as name, contact details, and registration information.
      Implements SCD Type 2 for tracking changes over time.
    columns:
      - name: dim_user_id
        description: "Surrogate primary key for the user dimension."
        tests:
          - not_null
          - unique

      - name: user_hkey
        description: "Hash key from hub_users for unique user identification."
        tests:
          - not_null

      - name: user_id
        description: "Business identifier for the user."

      - name: user_name
        description: "Name of the user."

      - name: email
        description: "Email address of the user."

      - name: phone_number
        description: "User's contact number."

      - name: address
        description: "User's address."

      - name: birthdate
        description: "User's date of birth."

      - name: registration_date
        description: "Date the user registered."

      - name: valid_from
        description: "Start date of this version of the user record."
        tests:
          - not_null

      - name: valid_to
        description: "End date of this version of the user record."
        tests:
          - not_null

  - name: dim_product
    description: >
      Dimension table for products enriched with aisle and department information.
      Uses SCD Type 2 logic to track changes over time.
    columns:
      - name: dim_product_id
        description: "Surrogate key for the product dimension."
        tests:
          - not_null
          - unique

      - name: product_hkey
        description: "Hash key from the hub_product table."
        tests:
          - not_null

      - name: product_id
        description: "Business key representing the product."

      - name: product_name
        description: "Name of the product."

      - name: aisle_id
        description: "Foreign key to the aisle."

      - name: aisle
        description: "Descriptive name of the aisle."

      - name: department_id
        description: "Foreign key to the department."

      - name: department
        description: "Descriptive name of the department."

      - name: created_at
        description: "Timestamp when the product was created."

      - name: updated_at
        description: "Timestamp when the product was last updated."

      - name: valid_from
        description: "Start timestamp for the validity of this dimension record."
        tests:
          - not_null

      - name: valid_to
        description: "End timestamp for the validity of this dimension record."
        tests:
          - not_null

  - name: fact_user_activity
    description: >
      Fact table capturing user activity including add-to-cart and reorder behavior,
      enriched with product and order data.
    columns:
      - name: fact_user_activity_id
        description: "Surrogate primary key for the fact_user_activity table."
        tests:
          - not_null
          - unique

      - name: dim_user_id
        description: "Foreign key to dim_user representing the user."
        tests:
          - not_null

      - name: dim_product_id
        description: "Foreign key to dim_product representing the product."
        tests:
          - not_null

      - name: product_name
        description: "Name of the product."

      - name: order_id
        description: "Foreign key to hub_order representing the order."
        tests:
          - not_null

      - name: order_number
        description: "Sequential number of the order."

      - name: add_to_cart_order
        description: "The sequence in which the product was added to cart."

      - name: add_to_cart_time
        description: "Timestamp when the product was added to cart."

      - name: reordered
        description: "1 if the product was reordered, else 0."

      - name: activity_type
        description: "Type of activity - 'add_to_cart', 'reorder', or 'other'."

      - name: load_timestamp
        description: "Timestamp of when the record was loaded into the fact table."

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['order_id', 'dim_user_id']

  - name: fact_order
    description: "Fact table capturing order-product-user relationships."
    columns:
      - name: fact_order_id
        description: "Surrogate primary key for the fact_order table."
        tests:
          - not_null
          - unique

      - name: dim_user_id
        description: "Foreign key reference to dim_user."
        tests:
          - not_null

      - name: dim_product_id
        description: "Foreign key reference to dim_product."
        tests:
          - not_null

      - name: order_id
        description: "Unique order ID."
        tests:
          - not_null

      - name: order_number
        description: "Sequential order number for the user."

      - name: order_created_at
        description: "Timestamp of order creation."
        tests:
          - not_null

      - name: order_dow
        description: "Day of the week the order was placed."

      - name: order_hour_of_day
        description: "Hour of the day the order was placed."

      - name: days_since_prior_order
        description: "Number of days since the prior order."

      - name: product_name
        description: "Name of the product ordered."

      - name: department
        description: "Department associated with the product."

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['dim_product_id', 'order_id']